### ISSUE TITLE
ATL.applyCustom is not a function

### ISSUE THREAD

**Issue by OmnesPotens** [kandashi/Active-Token-Lighting#123]
**Describe the bug**
The "applyCustom" function doesn't exist in ATL.

```
activeLighting.js:369 Uncaught (in promise) TypeError: ATL.applyCustom is not a function
[Detected 2 packages: ATL, dae]
    at ATL.apply (activeLighting.js:369:28)
    at ATL.applyEffects (activeLighting.js:311:34)
    at Object.fn (activeLighting.js:97:44)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12824:13)
    at foundry.js:12804:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12804:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12672:17)
    at async ActiveEffect5e.updateDocuments (commons.js:6153:23)
    at async ActiveEffect5e.update (commons.js:6250:23)
    at async DAEActiveEffectConfig._updateObject (DAEActiveEffectConfig.js:301:9)
    at async DAEActiveEffectConfig._onSubmit (foundry.js:5916:7)
    at async DAEActiveEffectConfig.submit (foundry.js:6237:5)
```

**To Reproduce**
1. Install and activate ATL and/or DAE
2. Create an Active Effect
3. During configuration select the "Custom" change mode

**Expected behavior**
There should be an "applyCustom" function or it should be removed if not used.

**Environment:**
 - OS: Windows, Ubuntu
 - Browser: Chrome
 - Foundry Version: v10
 - Module Version: 0.4.03
 - All Modules Disabled: No
 - Module List if no: 
   - ATL
   - DAE
   - Midi-QoL
   - Convenient Effects
   - Perfect Vision

**Comment by kaelad02** [comment]
version 0.5.2 has this fix
